### ISSUE TITLE
HowTos

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/cassiopeia#1]
Hello!
Can anyone explain what this is and how it's used?

$wa   = $this->getWebAssetManager();

// Enable assets
$wa->usePreset('template.cassiopeia.' . ($this->direction === 'rtl' ? 'rtl' : 'ltr'))
	->useStyle('template.active.language')
	->useStyle('template.user')
	->useScript('template.user');

$wa->registerStyle

$this->getPreloadManager()

Thank you!

**Comment by chmst** [comment]
Add also documentation of the Metismenu - 2 sublevels maximum.

**Comment by chmst** [comment]
local hosted fonts - why local hosted (GDPR) - what can the user do to expand or change his fonts.  https://github.com/joomla/cassiopeia/pull/61

**Comment by chmst** [comment]
@coolcat-creations : what is needed to close this issue?

**Comment by chmst** [comment]
Closing this, as the question was answered.
