### ISSUE TITLE
[RFC] Blog 2 column layout breaks column within the article

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#104]
### The question

Since the font size had been dramatically increased it became more visible than before:

The 2 column layout for the "Blog" page breaks from column 1 to column 2 in the middle of an article:

![2020-09-23_1](https://user-images.githubusercontent.com/7413183/94054385-e0d5e200-fddb-11ea-8a5d-a8592fff2681.png)

![2020-09-23_2](https://user-images.githubusercontent.com/7413183/94054396-e3d0d280-fddb-11ea-895c-c220604f7405.png)

Is this desired?

**Comment by chmst** [comment]
It is the "mansonry" layout. This tries to fill the columns so that have equal lenght.  
But you are right that this class does not fit here. I will change the class in sample data.

**Comment by richard67** [comment]
Solved with PR #96 .
