### ISSUE TITLE
Reminder: Run code style checks locally before going live with a pull request for the CMS

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#105]
We don't have those fancy checkin tools in our repo here like the CMS has for running code style, unit and system tests and so on.

We should run as many code style checks as possible locally and fix all issues found by these tests before we make the PR for the CMS so that we don't have many code style errors in that CMS at the beginning, because that would make it look unprofessional.

**Comment by drmenzelit** [comment]
I use Visual Studio Code for the Cassiopeia stuff and I have stylelint with the style rules from Joomla. It works very well for scss/css.
For the PHP things I'm not sure...

**Comment by richard67** [comment]
Then you do the scss/css stuff, and I care for the PHP. No idea about javascript yet.

**Comment by hans2103** [comment]
Using PHPStorm with Joomla Codestyle activated

**Comment by richard67** [comment]
> Using PHPStorm with Joomla Codestyle activated

No. We should use the tools which drone will use, as can be seen in drone.yml.

See PR #205 for the PHPCS part.

**Comment by richard67** [comment]
For js, drone uses `npm run lint:js`. This did not report any problems.

For scss, drone uses `npm run lint:css`. This reports problems (but not for files changed by us here in this repository) and fails with error. We have to check if this remains when I will update the branches in this repository to latest 4.0-dev or the CMS repository.

**Comment by richard67** [comment]
For SCSS see #235 .

**Comment by richard67** [comment]
All done.
