### ISSUE TITLE
Buttons vertically high

### ISSUE THREAD

**Issue by Quy** [joomla/cassiopeia#106]
### Steps to reproduce the issue
Go to Compact Tagged page

### Actual result
![buttons](https://user-images.githubusercontent.com/368084/94181333-30f08b00-fe54-11ea-8038-b276d8d36289.png)

**Comment by hans2103** [comment]
I cannot reproduce the issue with joomla/cassiopeia#development 

<img width="743" alt="Schermafbeelding 2020-09-25 om 08 57 39" src="https://user-images.githubusercontent.com/639822/94236241-2f36ce00-ff0d-11ea-9096-7c4085d8e2ae.png">

**Comment by Quy** [comment]
It is reproducible on Firefox 81.0 on Windows 10.

**Comment by chmst** [comment]
Seems that the listlimit selector makes strange effects 
![grafik](https://user-images.githubusercontent.com/1035262/94300716-b3b73a00-ff69-11ea-8f31-2accfdd2481b.png)

**Comment by drmenzelit** [comment]
Solved with PR #151
