### ISSUE TITLE
Pagination - Remove borders?

### ISSUE THREAD

**Issue by Quy** [joomla/cassiopeia#107]
### Steps to reproduce the issue
Is it intentional to have borders on disabled buttons?

### Actual result
![pagination](https://user-images.githubusercontent.com/368084/94182463-e6700e00-fe55-11ea-905d-ef5d23a956ad.png)

**Comment by hans2103** [comment]
Took me a while to find one. 
/index.php/article-category-list

**Comment by hans2103** [comment]
it seems to be intentional on disabled items. But I agree it is ugly.
Active links have white border.

**Comment by richard67** [comment]
I'd prefer them to all have this light grey border, enabled and disabled.

**Comment by hans2103** [comment]
Created PR https://github.com/joomla/cassiopeia/pull/116
