### ISSUE TITLE
Add spacing

### ISSUE THREAD

**Issue by Quy** [joomla/cassiopeia#108]
### Actual result
![99](https://user-images.githubusercontent.com/368084/94183087-ba08c180-fe56-11ea-857f-cad907f7c669.png)

**Comment by richard67** [comment]
I've just updated the development branch here with latest changes from 4.0-dev. Possibly this has solved the issue here. Someone should check that.

**Comment by hans2103** [comment]
@Quy after running `npm ci` on this repo and installing "Sample Data Blog" the Cassiopeia looks like the following screenshots on my screen:

<img width="1523" alt="Schermafbeelding 2020-09-24 om 21 35 26" src="https://user-images.githubusercontent.com/639822/94191571-fa475e80-fead-11ea-80a8-938a4e89e703.png">
<img width="1523" alt="Schermafbeelding 2020-09-24 om 21 35 33" src="https://user-images.githubusercontent.com/639822/94191584-ffa4a900-fead-11ea-8933-557b7010bf0d.png">


After installing "Testing Sample Data" I can confirm the issue. (both Sample Data Blog as Testing Sample Data are installed now)

<img width="1523" alt="Schermafbeelding 2020-09-24 om 21 37 14" src="https://user-images.githubusercontent.com/639822/94191733-42668100-feae-11ea-8875-c95c74aa4fdb.png">
