### ISSUE TITLE
Ready for testing

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#109]
Is it helpful for others to test at this time or is it preferred to wait?

**Comment by chmst** [comment]
Yes, please test :) 
Of course it is still work in progress but there are modules and different layouts which are not in sample data.

**Comment by brianteeman** [comment]
I ask because I wouldnt want to bombard you with questions if those parts are " to be done"

**Comment by richard67** [comment]
All work we have done up to now can be found in the development branch. There is also a dummy PR #48 for testing with a link to an installation package for testers without git, composer and npm.

**Comment by richard67** [comment]
I've just updated everything by the latest changes in the 4.0-dev branch of the CMS and made a new installation package.
