### ISSUE TITLE
RFC: Do we need a basic fontsize as parameter? 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#11]
See Backend - the basic fontsize is variable, with default 16px but webdesiger can select another basic fontsize. 

Can or should we have such a parameter?

**Comment by drmenzelit** [comment]
If we want to make Cassiopeia accessible we should use relative font sizes. I find this article very interesting:
https://css-tricks.com/accessible-font-sizing-explained/

**Comment by chmst** [comment]
This is already in cassiopeia. Basic fon-size is 14px, see _variables.scss. 
The Fonts variables are calculated based in the Font Fira. 

Maybe this is not matching other fonts. Some fonts are rather small and would need a bigger (or smaller) $font-size-root. 
BUT then every other font-size and line height must be calculated.

**Comment by drmenzelit** [comment]
font-size 14px is small... browser have normally 16px as basis size...

**Comment by hans2103** [comment]
I we want to make Cassiopeia accessible we should use `1em` as a basic font-size. 
Doing so it will use the default browser font-size as fallback. In my case 16px, while my mother uses 20px.

**Comment by brianteeman** [comment]
> Some fonts are rather small and would need a bigger (or smaller) $font-size-root.

You should also be aware that it is quite common for non latin character fonts to be very small

**Comment by chmst** [comment]
Releated https://issues.joomla.org/tracker/joomla-cms/29411

**Comment by drmenzelit** [comment]
Done with PR #75
