### ISSUE TITLE
Wrong spacing on filters

### ISSUE THREAD

**Issue by hans2103** [joomla/cassiopeia#111]
Joomla 4 with "Testing Sample Data"
url => index.php/recipes

<img width="534" alt="Schermafbeelding 2020-09-24 om 22 11 38" src="https://user-images.githubusercontent.com/639822/94195159-f23ded80-feb2-11ea-9132-42110de3aed6.png">

**Comment by chmst** [comment]
see https://issues.joomla.org/tracker/joomla-cms/29504

**Comment by hans2103** [comment]
please no references to issues.joomla.org but to github issues.

**Comment by drmenzelit** [comment]
https://github.com/joomla/joomla-cms/issues/29504

**Comment by hans2103** [comment]
created pr https://github.com/joomla/joomla-cms/pull/30761
