### ISSUE TITLE
Padding Top system message container

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#115]
### Steps to reproduce the issue
Clean install of development
Click on login without any credentials

### Expected result
![image](https://user-images.githubusercontent.com/1296369/94196208-f0bcf700-feab-11ea-9a11-ba86476ea18c.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/94196252-ffa3a980-feab-11ea-965f-2dfa9fc63b0e.png)

**Comment by hans2103** [comment]
Created PR https://github.com/joomla/cassiopeia/pull/132

**Comment by hans2103** [comment]
Closing this issue, since PR is created.
