### ISSUE TITLE
custom module in sample data 

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#118]
### Steps to reproduce the issue
current development branch
install sample data

### Expected result
Clean display on desktop and mobile

### Actual result
on some mobile devices the height of the module obscures some of the body

![image](https://user-images.githubusercontent.com/1296369/94197844-4397ae00-feae-11ea-89d1-cbb6b93a0259.png)

**Comment by chmst** [comment]
Closing this as resolved
