### ISSUE TITLE
Column width mobile

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#119]
### Steps to reproduce the issue
Install current development branch with sample data

### Expected result
Columns are positioned with equal left/right margins

### Actual result
Depending on the mobile device there is either no right margin or there is a horizontal scroll

![image](https://user-images.githubusercontent.com/1296369/94198135-b1dc7080-feae-11ea-879c-a8cbfdd86408.png)

![image](https://user-images.githubusercontent.com/1296369/94198242-e3edd280-feae-11ea-9b56-cbb925f62f7f.png)

**Comment by drmenzelit** [comment]
Should be resolved with https://github.com/joomla/joomla-cms/compare/4.0-dev...drmenzelit:patch-1

**Comment by richard67** [comment]
https://github.com/joomla/joomla-cms/pull/30781

**Comment by brianteeman** [comment]
Closing as I have tested the pr - thanks

**Comment by richard67** [comment]
Meanwhile PR [https://github.com/joomla/joomla-cms/pull/30781](https://github.com/joomla/joomla-cms/pull/30781) has been merged in the CMS repo, and the branches of this repo have been updated to latest 4.0-dev of the CMS, so the fix has meanwhile arrived here, too.
