### ISSUE TITLE
Module title size

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#120]
### Steps to reproduce the issue
install current development branch with sample data

### Expected result
module titles are visually and semantically the same 

### Actual result
A mix of h3 and h4 titles
![image](https://user-images.githubusercontent.com/1296369/94198514-4a72f080-feaf-11ea-92c7-ccf396ef529a.png)

### Additional comment
and preferably h3 to prevent a skipped heading level accessibility issue

**Comment by drmenzelit** [comment]
@chmst can this be changed on sample data?

**Comment by richard67** [comment]
> @chmst can this be changed on sample data?

As Christiane might be busy: I think yes.

**Comment by chmst** [comment]
It was inherited  ;) but yes

**Comment by chmst** [comment]
@richard67 the modules login_form and main-menu are stored during the installation. There is no headertag defined and obviously the default value for header_tag is h4. 
h4 as default is surely wrong. 
So there are two ways: 
- either the installation sql stores the "header-tag":"h3" for these modules 
- or the default value for rendering modules is adapted (imho the better way) 
-or both 

in any case this is an issue for the core, not cassiopeia.

**Comment by richard67** [comment]
Oh, I see.

**Comment by chmst** [comment]
While it is correct that in installation data the header-tag is missin, I have found the wrong default falue in the chrome. Closing this as we have a PR
