### ISSUE TITLE
Articles with Linked titles and linked images

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#121]
### Steps to reproduce the issue
install current development branch with sample data

### Expected result
Good accessibility

### Actual result
Because the intro image is a link and the title is an identical link we have an accessibility problem

**What It Means**
Adjacent links go to the same URL.
**Why It Matters**
When adjacent links go to the same location (such as a linked product image and an adjacent linked product name that go to the same product page) this results in additional navigation and repetition for keyboard and screen reader users.

**Standards and Guidelines**
2.4.4 Link Purpose (In Context) (Level A)

**Comment by chmst** [comment]
I am closing this as we have a PR
