### ISSUE TITLE
Ambiguous Link names on images

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#123]
### Steps to reproduce the issue
Install current development branch and sample data

### Expected result
Accessible content with unique and named links

### Actual result
All of the intro images are unlabelled links. They are just announced by a screenreader as `link` without any indication of what they are a link to

**Comment by chmst** [comment]
You ar right, the images in sample data are still work in progress.

**Comment by chmst** [comment]
@brianteeman We should resolve this in joomla-cms. If there is a readmore or title then a extended link for the woleard as you have suggested is best solution.

**Comment by brianteeman** [comment]
Please leave this open until I get a spare moment to look at creating a pr for this in joomla-cms. It will act as a reminder

**Comment by chmst** [comment]
I think the best ist: 
if there is the param "link-title" OR a readmore then the whole card sas a whole chould be a single link. 

When I think about this, it would als be great for items in the blog. Then it is simple for users and no duplicate links can occur

**Comment by brianteeman** [comment]
I dont agree - it would mean we would have to rename the terminology etc

I will work on it tomorrow

**Comment by brianteeman** [comment]
Closing now I have created a PR in the main repo as promised https://github.com/joomla/joomla-cms/pull/30823
