### ISSUE TITLE
Author login

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#127]
### Steps to reproduce the issue
Install current development branch and sample data

### Expected result
Sample data that follows best practices - especially duplicate links

### Actual result
http://localhost/cass/index.php/author-login-1
http://localhost/cass/index.php/author-login

At least one of those should be an alias to the other. That will give just a single url and showcase another feature of joomla the system alias menu

**Comment by richard67** [comment]
> At least one of those should be an alias to the other. That will give just a single url and showcase another feature of joomla the system alias menu

Agree. @chmst Would you like to fix that?

**Comment by chmst** [comment]
Closing this for now as there is a PR

**Comment by richard67** [comment]
merged
