### ISSUE TITLE
Prev Next cosmetic

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#128]
### Steps to reproduce the issue
Install current development branch and sample data

This could be a matter of taste but visually it looks like the navigation is indented for no reason and breaks the flow of the page

When you hover on the link it is clear why the indent was present. Perhaps the non-hover state should also have a background

`
![2020-09-24_22-39-14](https://user-images.githubusercontent.com/1296369/94203382-37641e80-feb7-11ea-99e8-cbadcfc0a85d.png)
![chrome_2020-09-24_22-39-42](https://user-images.githubusercontent.com/1296369/94203385-37fcb500-feb7-11ea-912a-e2ed3c4aa61b.png)

**Comment by hans2103** [comment]
@brianteeman can you add a link where this issue can be seen? I don't know the entire Sample Data by heart.

**Comment by brianteeman** [comment]
Any page that has a prev or next button
eg
sample-layouts/category-list/75-your-modules

**Comment by hans2103** [comment]
Issue is solved when https://github.com/joomla/cassiopeia/pull/131 is merged

**Comment by richard67** [comment]
Solved with #131 . Feel free to re-open if this is not the case. Further improvements on these buttons may happen with future PR's.

**Comment by brianteeman** [comment]
@richard67 #131 made no change to this - please re-open as I dont have permissions to do that

**Comment by richard67** [comment]
@brianteeman Hmm, to me it seemed to be ok when I've tested. Could you test again on the development branch? I'll re-open your issue meanwhile, if the test is ok you can close it again.

**Comment by brianteeman** [comment]
Of course I checked with the development branch and saw no changes but please could you post a screenshot of what you saw

**Comment by richard67** [comment]
The prev and next buttons have light grey borders also when not hovered.

Here below the first of the 3 articles in the sequence, the right border of the "Next" button seems to be aligned well with the right edge of the text:

![2020-09-25_4](https://user-images.githubusercontent.com/7413183/94312179-bc653b80-ff7c-11ea-84ac-d7702c860e41.png)

Below the 2nd article, the left border of the "Prev" button seems to be well aligned with the left edge of the text.

But what I see right now is that on the right hand side, the text and the button are not aligned, the end of the text in the 2nd last line seems to be more right than the right border of the button:

![2020-09-25_5](https://user-images.githubusercontent.com/7413183/94312196-bff8c280-ff7c-11ea-8813-f26b7fd0bbb6.png)

Finally the 3rd and last article in the sequence - the "Prev" button seems to be well aligned.

![2020-09-25_6](https://user-images.githubusercontent.com/7413183/94312209-c38c4980-ff7c-11ea-97eb-47616e41810b.png)

Conclusion: To me it looks much better than in your screenshot here in the issue. The "Prev" button is well aligned. But on a second look the "Next" button needs to be optimized a bit, moved a bit to the right.

Strange that for you it looks so different.

Have you checked other articles, e.g. from testing samle data? If so, which ones? I will try to reprocude.

Or is there something very sticky in your browser's cache? But here I did not need to clear the cache to see the result, and after clear it still is fine.

**Comment by brianteeman** [comment]
Really weird. git was saying my branch was up to date. refreshed it about 5 times. nothing. 6th time it found the recent merges and all good now.

**Comment by chmst** [comment]
What do you think about having both buttons centered below the text instead of left / right? 
![grafik](https://user-images.githubusercontent.com/1035262/94314874-c63d6d80-ff81-11ea-9f80-555cd15e5fb6.png)

In a big screen we can see both buttons at once and do not need big eye movements.

**Comment by brianteeman** [comment]
Can't say I have ever really thought about it.

**Comment by richard67** [comment]
If it was really centered it could be ok, but in the screenshot above it appears not really centered, even if it shows a part only.

And that would look ugly, if not exactly in the middle.

And it would only look good when the text area has a border or when text is left and right justified (what we call in German "Blocksatz", don't find the English term now, so that we really can see it is in the middle.

But as soon as text is justified left side only and there is no card or border or box around it, it looks ugly in my opinion. That's just my personal taste.

**Comment by chmst** [comment]
This is not a pr :) it is a fake screenshot and of course, the buttons must be centered correctly.  It is more a question of UX. Your eyes now must search the next / prevoius button on a big screen.

**Comment by richard67** [comment]
Regarding UX it would be in fact better, not only because shorter eye movement but also shorter mouse movement for fast paging forward and backward.

If you can make it look good, I could like it.

**Comment by brianteeman** [comment]
The benefit would really depend on the width of the content AND if you are displaying the title  in the next page link or not. If I look at the pagination on my latest site a change to centred would make it worse not better because ot the different sizes of the links.

eg
### Current
![image](https://user-images.githubusercontent.com/1296369/94316871-1960f180-ff7d-11ea-9fe1-d123a0ad1005.png)

### Centred
![image](https://user-images.githubusercontent.com/1296369/94316972-43b2af00-ff7d-11ea-9802-57debe8c6819.png)

**Comment by chmst** [comment]
This is a good argument. It depends ..

**Comment by richard67** [comment]
Oh yes.
