### ISSUE TITLE
Search Button

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#133]
### Steps to reproduce the issue
Install development branch and sample data

### Expected result
search button placed next to search box

### Actual result
On some mobile resolutions the search button is wrapped to the next line
![image](https://user-images.githubusercontent.com/1296369/94235442-7ddf6a80-ff03-11ea-947f-fe02a25fc5d9.png)

**Comment by hans2103** [comment]
@drmenzelit created a PR for this issue: https://github.com/joomla/cassiopeia/pull/135
