### ISSUE TITLE
sidebar module truncated

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#134]
### Steps to reproduce the issue
Install development branch and create some modules in the sidebar-right position

### Expected result
all the modules are displayed 

### Actual result
The bottom of the last module is not displayed

This image shows that that the spacing below the image and the bottom border of the module is missing when displayed on mobile
![image](https://user-images.githubusercontent.com/1296369/94236177-b0d62e00-ff04-11ea-92c8-1e5ab80090e7.png)

**Comment by richard67** [comment]
Solved with PR #144 .
