### ISSUE TITLE
Enable selfhosting of selected Google fonts

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#14]

**Comment by richard67** [comment]
I've prepared a target branch for this work: [https://github.com/joomla/cassiopeia/tree/4.0-dev-google-fonts-enhancements](https://github.com/joomla/cassiopeia/tree/4.0-dev-google-fonts-enhancements).

I suggest to make pull request(s) against this branch for the implementation.

**Comment by richard67** [comment]
Has been solved with PR #18 and then later been improved with diverse PR's, final one was #61 ^.
