### ISSUE TITLE
Missing grid-gutter above the content area

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#140]
### Steps to reproduce the issue
Missing grid-gutter above the content area 

from @richard67 

There is no space betwen the grey frame of the breadcrumbs module and the heading, while for the sidebar modules there is. Shall it be fixed with this PR here or with another, future one?

**Comment by hans2103** [comment]
Screenshot please

**Comment by richard67** [comment]
"This PR here" refers to #138 where I posted my comment with a screenshot.

**Comment by hans2103** [comment]
fixed in https://github.com/joomla/cassiopeia/pull/132

**Comment by hans2103** [comment]
and relates to https://github.com/joomla/joomla-cms/pull/30760

**Comment by chmst** [comment]
#132 works, thank you
