### ISSUE TITLE
Links in blog and featured 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#146]
I have made a PR https://github.com/joomla/joomla-cms/pull/30788

It is for link lists in views blogs and featured. At the moment, the ordered list is displayed with numbers. 

![grafik](https://user-images.githubusercontent.com/1035262/94373058-0c6e0a80-0103-11eb-803d-9eafadc51dbe.png)

The link lists needs some styling 

And maybe it can be improved for UX and a11y.

**Comment by richard67** [comment]
PR https://github.com/joomla/joomla-cms/pull/30788 has been merged this morning in the CMS repo, and just now I have updated the branches of this repo to latest 4.0-dev on the CMS, so the change has arrived here, too. Can this issue be closed now, or are there some aspects still to be solved?

**Comment by chmst** [comment]
Thank you. It is a first step, but it can be improved, as there are still tow links if the title is linked and the readmore is active. So pleas let it open

EDIT - sorry confised issues. ;) We can close this
