### ISSUE TITLE
system-message-container displays margin-top 15px even when empty

### ISSUE THREAD

**Issue by Scrabble96** [joomla/cassiopeia#159]
### Problem identified
When a module is used in the main-top position there is quite large gap between it and the component content. This is partly due to the system message container displaying a 15px margin top even when there is no message to display. 

If the main-top position is not used, then the system message container top margin does not display.

### Proposed solution
Remove the code that displays the system message container as outlined above.

**Comment by drmenzelit** [comment]
We have already a PR dealing with this (#132), but we need more improvements

**Comment by richard67** [comment]
> We have already a PR dealing with this (#132), but we need more improvements

Not really. The PR which deals with the "when there is no message to display" aspect is joomla/joomla-cms#30760 , see my comment in the PR you have mentioned: https://github.com/joomla/cassiopeia/pull/132#issuecomment-701384248

**Comment by chmst** [comment]
@Scrabble96 canwe close this one?

**Comment by Scrabble96** [comment]
Ok. But I've added a comment to #132
