### ISSUE TITLE
Sample data photos. Sample data photos are old and old fashioned.

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#17]
The photos used in Joomla sample data look rather old and not attractive. New images should be added to the sample data.
Joomla (marketing) has a license to 123rf.  
@marcodings can help here.

**Comment by brianteeman** [comment]
Pretty certain that we would not be able to use the images from 123rf as that would be "distributing" the images and not using them for "marketing" which is usually excluded.

You can find great cc0 licenced images at either pexels.com or unsplashed.com

**Comment by chmst** [comment]
Changing images in sample data is easy. The question is mor "which images". This isa an example with images from the nasa.
Meanings are different - is this too much? 

![grafik](https://user-images.githubusercontent.com/1035262/94723272-c5795280-0358-11eb-89b5-60e1dfea90c6.png)

**Comment by brianteeman** [comment]
They are fine for me

**Comment by richard67** [comment]
Well at least they are different, so the random image module would make sense ;-)

**Comment by chmst** [comment]
Closing this as there is a PR #248 for blog sample data.
Testing sample data is not in scope of this project.
