### ISSUE TITLE
Z-index issue with Google invisible captcha

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#170]
### Steps to reproduce the issue

See https://github.com/joomla/joomla-cms/issues/29722

Should maybe be fixed in the Cassiopeia and not the CMS repository.

**Comment by hans2103** [comment]
created PR https://github.com/joomla/joomla-cms/pull/31454

**Comment by chmst** [comment]
closing this as there is a PR. Thank you @hans2103
