### ISSUE TITLE
Colours in cassiopeia

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#171]
### What needs to be fixed
Due to a11y contrast ratio we have now a colour for links which is hardly to see. 

### Why this should be fixed
As for example on this site - you hardly see a difference in the breadcrumbs.

![grafik](https://user-images.githubusercontent.com/1035262/95313485-79ff0100-0890-11eb-9664-847299b88c96.png)

### How would you fix it
Go back to the original colour #006898 as primary colour
It is a beautiful colour with good contrast ratio. 

![grafik](https://user-images.githubusercontent.com/1035262/95317138-08758180-0895-11eb-8773-6459efbb5a6c.png)

Or designers have a better idea. 

### Side Effects expected
don't know.

**Comment by richard67** [comment]
But does that colour fit to the template colours? The original bootstrap blue for links and buttons looked ugly together with the Cassiopeia header area.

**Comment by chmst** [comment]
I am not a designer. And it must not be this colour, of course, every other with good contrast ratio is accepted
The place where a primary button is in direct contact with the template colour is the search button in the header. So mybe we could choose a different colour for primary in the header? 

@coolcat-creations proosed the new color https://www.pantone.com/color-finder/14-4811-TPX which matches the template colour, this is not suitable for text, but very nice on a dark background, or as background with black colour.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #177 .
