### ISSUE TITLE
Deactivate language debugging when storing sample data

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#185]
### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/issues/31160

**Comment by richard67** [comment]
Hmm, basically this should be fixed in the CMS repo because it's a bug and not related to our sample data enhancements here.

Or am I wrong?

**Comment by chmst** [comment]
I have opened it in joomla-cms https://github.com/joomla/joomla-cms/issues/31160
this is a reminder
