### ISSUE TITLE
Metis Menu does not work for third level menu items

### ISSUE THREAD

**Issue by Scrabble96** [joomla/cassiopeia#190]
### Steps to reproduce the issue
Install PR #48 package dated 20/10. and sample blog
Add a menu separator item under the Main Menu Blog > Sample Layouts > Articles item
Add a new menu item under that separator

### Expected result
There should be a dropdown triangle next to the separator to reveal the items below

### Actual result
There is no triangle:
![third-level-metis-horizontal](https://user-images.githubusercontent.com/36987494/96717233-0c79c700-139e-11eb-85c9-e837e12af829.jpg)

![third-level-metis-vertical](https://user-images.githubusercontent.com/36987494/96717246-100d4e00-139e-11eb-9215-7b3a992de380.jpg)

### System information (as much as possible)

Looking at the code in inspector, it seems that the next menu item is not being added to the li

**Comment by richard67** [comment]
@Scrabble96 That's a known limitation of the metismenu, as far as I know. @chmst Can you confirm this?

**Comment by chmst** [comment]
We have decided to have 2 levels to keep the metismenu accessible. 
We will need a documentation for this restriction

**Comment by richard67** [comment]
@chmst We have 3 levels: Top level, then one below and then another one, not 2 like you write, except if you only count the sub-levels. Did you mean that, 2 sub-levels?

Other question: Would it make sense not to output those levels which cannot be shown anyway, i.e. stop with level 3 (or submenu level 2)? Currently the menu items are in the html, they are just never visible.

**Comment by brianteeman** [comment]
> We will need a documentation for this restriction
It will need more than documentation it MUST go in the module description otherwise this will be a huge cause of bug reports especially as this has been done as a layout and not a separate module.

![image](https://user-images.githubusercontent.com/1296369/96725469-cd9d3e80-13a8-11eb-84d0-3d9f42fc3f53.png)

In fact the more I think about it if there is going to be this restriction then it must be a separate module and not a layout.

> Currently the menu items are in the html, they are just never visible.
I can not confirm that. But it does incorrectly mark the menu item as parent

**Comment by brianteeman** [comment]
Just deleted my last comment as it was completely wrong - sorry

The menu does display ALL the levels. You just have to make sure that the module is set to display all the levels by changing the end level in the options. (just as always)

![image](https://user-images.githubusercontent.com/1296369/96727074-929c0a80-13aa-11eb-9edc-9c0c44b53364.png)

![image](https://user-images.githubusercontent.com/1296369/96727160-ae071580-13aa-11eb-909d-e2564ac4ed57.png)

**Comment by richard67** [comment]
Oops, so we actually can do more than 3 levels? Then I was completely wrong, too, because I thought we couldn't.

**Comment by chmst** [comment]
I counted sub-levels (2) . And also was wrong with my assuption that we have a limit of 2 sublevels. 
I use to recommend this  as maximum for accessible sites

**Comment by Scrabble96** [comment]
Sorry to raise the alarm unnecessarily. Could I suggest that the default option is to show All levels? It may always have been that you select the number of levels you want, but for anyone new to Joomla they wouldn't necessarily realise or notice this and assume that all are displayed automatically.

**Comment by Scrabble96** [comment]
BTW, what is the difference between a separator used as a heading and the 'menu heading' item type?

**Comment by Scrabble96** [comment]
I'll close this, but I'd still like an answer to the above.

**Comment by richard67** [comment]
> Could I suggest that the default option is to show All levels?

That's something which either would have to be done for all frontend menus, or we have to override the xml file with the menu module options, too-

@chmst @drmenzelit Do we really want that, have a modified XML? Or should that be done for any kind of frontend menu, metismenu or not? If the first, it has do be done here in this repo, if the latter, then it has to be done in the CMS repo.

> BTW, what is the difference between a separator used as a heading and the 'menu heading' item type?

There is not really a difference except that they have a different css class so they can be styled differently, as far as I understand the PHP code.

**Comment by chmst** [comment]
No, we do not modify the XML here in Caasiopeia.

**Comment by brianteeman** [comment]
Sorry that is not correct the sample data does use different values for the levels in the module to the default

https://github.com/joomla/cassiopeia/blob/development/plugins/sampledata/blog/blog.php#L1170-L1171

and the default is to end at all
