### ISSUE TITLE
Accessible Module Search in frontend

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#20]
The search module in cassiopeia need a11y test in every variant, just as confirmation. AXE and Wave say that the form is ok. 

- [ ] with label and / or icon
- [ ] in extended form 
- [ ] as a component
- [ ] With search results 
- [ ] on different places

**Comment by richard67** [comment]
Branch prepared for this task: https://github.com/joomla/cassiopeia/tree/4.0-dev-frontend-search

**Comment by hans2103** [comment]
@richard67 pr created
https://github.com/joomla/cassiopeia/pull/30

**Comment by hans2103** [comment]
form itself looks fine to me. Even on different places.

**Comment by hans2103** [comment]
@chmst 
- created PR joomla/joomla-cms#30528 to solve the legend issue.
- created PR joomla/joomla-cms#30534 to solve styling of search results
- created PR joomla/joomla-cms#30535 to add statement of search results

**Comment by chmst** [comment]
All PRs merged, so we can close this issue
