### ISSUE TITLE
[Request for Comment] Rename the "metismenu" layout to something more meaningful

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#208]
### Problem identified

See @brianteeman 's comment here [https://github.com/joomla/cassiopeia/pull/195#issuecomment-715308105](https://github.com/joomla/cassiopeia/pull/195#issuecomment-715308105):

> Suggestion - rename the layout to "dropdown"
> At least then it describes what its a layout for instead of "metismenu" which has no meaning to the user

As the name of a layout which can be selected in a module's advanced options is determined by file names we have to rename files.

### Proposed solution

Rename the layout and so following files:
- (list will be completed soon)

### Open questions

Which new name shall we chose?

1. "dropdown" - Could be not specific enough if someone wants to add another kind of dropdown menu in that way in a template override or an own template based on Cassiopeia.
2. "dropdown-metismenu" - Could result in a bit long filenames but would be more clear than now. Curious users still can Google for "metismenu".
3. "dropdown-metismenujs" - Same as 2 but more precise. Would not lead to people asking in forums or issues "Does it load jQuery?".
4. Anything else?

**_Please report back your opinions and in case of 4 suggest a name. Thanks in advance_**

**Comment by chmst** [comment]
> "dropdown" - Could be not specific enough if someone wants to add another kind of dropdown menu in that way in a template override or an own template based on Cassiopeia. 

I would not use "metis" , as it is an artificial name (most users don't know who metis was). 

 "cassiopeiamenu" ?

**Comment by richard67** [comment]
> I would not use "metis" , as it is an artificial name (most users don't know who metis was).

Google is their friend.

**Comment by richard67** [comment]
I've meanwhile decided to use "dropdown-metismenu". Will be solved either with PR #217 or PR #221 .

**Comment by richard67** [comment]
For the layout selection in the menu module's advanced option I've meanwhile decided to use "Dropdown", see PR #217 or PR #221 .
