### ISSUE TITLE
All Tags - Full width display

### ISSUE THREAD

**Issue by Quy** [joomla/cassiopeia#209]
![all-tags](https://user-images.githubusercontent.com/368084/97465843-b3f77c00-18ff-11eb-855e-5b5ecda85709.png)

**Comment by chmst** [comment]
The layout of com_tags - default_items must be reviewed and changed, maybe better in the core - @drmenzelit ?

**Comment by chmst** [comment]
@drmenzelit could you look there? If it is for core or if it is for scss

**Comment by drmenzelit** [comment]
https://github.com/joomla/joomla-cms/issues/31388

**Comment by chmst** [comment]
Work in progress in the core, so cloing it here.
