### ISSUE TITLE
Metismenu javascript doesn't contain copyright information

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#213]
### Steps to reproduce the issue

Check file [templates/cassiopeia/js/mod_menu/menu-metismenu.js](https://github.com/joomla/cassiopeia/blob/development/templates/cassiopeia/js/mod_menu/menu-metismenu.js).

### Expected result

The file contains the usual copyright information at the top.

### Actual result

The file doesn't contains any copyright information.

### System information (as much as possible)

Cassiopeia development branch.

### Additional comments

Related issue: #212 . If we add copyright information, we should minify the file, and if we don't minify it we maybe shouldn't add copyright information, but the latter would be wrong.

**Comment by brianteeman** [comment]
Just add the copyright to the file and follow the instructions in #212

**Comment by richard67** [comment]
@brianteeman Question: Which years for the copyright? We have "2005 - 2020" in other Cassiopeia files. But now we have 2020. Would it be "2020 - 2020" then? Looks a bit silly. Or just "2020"?

**Comment by brianteeman** [comment]
So there has been a production department policy change on this and most files have not been updated. The original pr was done by @nibra for 2.10 iirc

**Comment by richard67** [comment]
Will be solved either with PR #217 or PR #221 .
