### ISSUE TITLE
 [Request for Comment] The template.js file of Cassippeia seems to be obsolete

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#214]
### Problem identified

It seems the template.js file of Cassippeia is obsolete, see [https://github.com/joomla/cassiopeia/pull/210#issuecomment-718201869](https://github.com/joomla/cassiopeia/pull/210#issuecomment-718201869).

### Proposed solution

Someone check and if that is true, correct it.

### Open questions

- Shall the file really be removed if it is obsolete, or shall it serve as a kind of template for template overrides?
- Shall it be done here or in the CMS repository?

**Comment by brianteeman** [comment]
What makes you think it is obsolete?

**Comment by richard67** [comment]
Dimitris' comment [https://github.com/joomla/cassiopeia/pull/210#issuecomment-718201869](https://github.com/joomla/cassiopeia/pull/210#issuecomment-718201869).

**Comment by brianteeman** [comment]
I would double check and then check again

**Comment by richard67** [comment]
Sure, that's why I made this RFC so not me only but others too can check that.

**Comment by richard67** [comment]
Closing as duplicate to #216 .
