### ISSUE TITLE
dropdown menu background

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#215]
The background of the dropdown disappears before the menu items - see how the link to Blog is still visible when the menu item collapses

![menucollapse](https://user-images.githubusercontent.com/1296369/97507821-ed6ace80-1975-11eb-8f1b-34f713101593.gif)

**Comment by richard67** [comment]
Confirmed, I've noticed that too when testing my PR.

@drmenzelit Could that be caused by the transition for the dropdown toggles?

**Comment by gostn** [comment]
similar https://github.com/joomla/joomla-cms/issues/28260

**Comment by drmenzelit** [comment]
I was not able to reproduce...

**Comment by richard67** [comment]
@drmenzelit You have checked with up-to-date development branch?

**Comment by richard67** [comment]
Solved with PR #263 . Will merge it now into the CMS PR.
