### ISSUE TITLE
Styling of popular tags - cloud layout

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#220]
### Steps to reproduce the issue
Make a module Popular tags. Choose cloud layout but no counting. 

### Expected result
A tag can be seen as a whole. 

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/97818111-c0355d80-1ca0-11eb-8189-5f7cf32dc2b9.png)

It is not visible where a tag ends. "New Feature Workflow" is one Tag .

Has to be done in joomla-cms

**Comment by brianteeman** [comment]
Isnt it just a css issue - adding a background?

**Comment by chmst** [comment]
Yes, you are right. Finally it is the user who decides how to stlye this.

**Comment by brianteeman** [comment]
I do think there should be a sensible default though.

**Comment by chmst** [comment]
I thought so, too, maybe a separator or a background. But it depends on parameters.

Are the numbers? They are in badges, so it is obvious what is in a tag and a background or separator would be too much.
Are there different font-sizes? If yes, a default-background looks bad. 

The layout could generate different classes for tags, depending on params (this is why I added the joomla-cms label). Or the user must decide how to style the class "tag-name".
