### ISSUE TITLE
tags and article filter

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#225]
### Steps to reproduce the issue
either create a tags list menu item or a category article list AND set the filter to display one of the options

### Actual result
![image](https://user-images.githubusercontent.com/1296369/98452303-e8600900-2145-11eb-983a-ce02932e63b6.png)

### Expected
![image](https://user-images.githubusercontent.com/1296369/98452339-50aeea80-2146-11eb-8204-1a6d62759de4.png)

**Comment by drmenzelit** [comment]
That is already solved:
https://github.com/joomla/cassiopeia/blame/edbaef6b94321bc8a3ecb76115b8b2e68204a316/templates/cassiopeia/scss/blocks/_global.scss#L58

![grafik](https://user-images.githubusercontent.com/9153168/98924737-75ec8180-24d5-11eb-8615-00aa2198c721.png)

Could you please test again?

**Comment by chmst** [comment]
Closing this as it is resolved.
