### ISSUE TITLE
Template Styles

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#228]
I was taking a look to see if we needed to add alt description etc to the site logo. 

As it currently defaults to have an alt="site name" I think that is fine.

But I did get a bit confused by the Title and Description fields

![image](https://user-images.githubusercontent.com/1296369/98542179-6d533b80-2288-11eb-9b53-abfe0619929d.png)

Title is only displayed if there is no logo displayed - thats fine but maybe it should indicate that

Description could probably be better described/labelled as "tagline"

**Comment by chmst** [comment]
Agreed. As native speaker you are invited to find a good label. I thought something like "Slogan" but "tagline" sounds good too. This is part of the core, could you make a PR for it?

**Comment by brianteeman** [comment]
Tagline is the generally accepted term from what I can tell

That still leaves the "image or Title" description issue

I brought it up here because its specific to cassiopeia and if I edit the core for this then it will make merging this template harder.

**Comment by chmst** [comment]
Closing this as it is resolved, thanks.
