### ISSUE TITLE
padding right in dropdown menu

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#230]
### Steps to reproduce the issue
Add a new menu item to the blog sample data menu.

Due to the padding around the dropdown arrow, the distance between the menu items looks buggy

![grafik](https://user-images.githubusercontent.com/1035262/98929527-8dc70400-24db-11eb-9e3a-c4377e367ff4.png)

**Comment by richard67** [comment]
I ~~plan to~~ will fix this with my PR #234 .

**Comment by richard67** [comment]
Will be solved with PR #234 , which is ready for testing now.
