### ISSUE TITLE
Styling and a11y  issue in frontend editing 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#232]
### Steps to reproduce the issue

https://issues.joomla.org/tracker/joomla-cms/29137

**Comment by chmst** [comment]
Styling is in TinyMCE.

**Comment by brianteeman** [comment]
What does tinymce have to do with the linked issue?

**Comment by richard67** [comment]
@brianteeman Maybe @chmst mixed up the issues, and her comment on TinyMCE refers to your issue #233 ?
