### ISSUE TITLE
Font differences betwen editor and site #30336

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#233]
See https://github.com/joomla/joomla-cms/issues/30336

**Comment by drmenzelit** [comment]
The solution posted in https://github.com/joomla/joomla-cms/issues/30336 will have the same effect as including the template.ccs from Cassiopeia as custom css in the configuration of TinyMCE

![grafik](https://user-images.githubusercontent.com/9153168/99438381-04b53000-2914-11eb-94b8-0c16cf492e6d.png)

See PR #246 for some improvements in font family and font size.

**Comment by drmenzelit** [comment]
Solved with PR #246
