### ISSUE TITLE
Template Param: use a colour palette

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#24]
### Feature Request

The user must be able to select a colour palette. In the backend template atum, this is possible.

We can either define some nice and a11y colour palettes or use the solution from atum. 

Most important: The solution must be fast.  

A colour palette must be accessible - contrast ratio, colour blindness.

**Comment by N6REJ** [comment]
is something like this helpful?
https://github.com/Simonwep/pickr

**Comment by chmst** [comment]
We may to have new dependencies if possible.  
We must evaluate the solution in the backend and need all information we can get, especially for concerning performance, as I remember controverse discussions.

**Comment by drmenzelit** [comment]
Parameter has been added. I'm closing the issue.
