### ISSUE TITLE
Back-to-top-link results in #top in URL

### ISSUE THREAD

**Issue by Scrabble96** [joomla/cassiopeia#242]
### Steps to reproduce the issue
Scroll down a page in Cassiopeia using the installation from PR48
Click the back-to-top link

### Expected result
Taken to top of page
No change of URL

### Actual result
Taken to top of page
BUT /#top appended to URL

### System information (as much as possible)
This doesn't happen in builds taken from the main Joomla github.

**Comment by particthistle** [comment]
Functionality looks to have changed in https://github.com/joomla/cassiopeia/pull/169 when `id="back-top"` was removed, which was the id used in the template.js to trigger the home scroll.

This then disables the JS in template.js that triggers back-to-top without the need for the #top. 

The template.js may however now be on it's way out, based on discussion in https://github.com/joomla/cassiopeia/issues/216

index.php
https://github.com/joomla/cassiopeia/blame/development/templates/cassiopeia/index.php

Template.js
https://github.com/joomla/cassiopeia/blame/development/templates/cassiopeia/js/template.js

**Comment by drmenzelit** [comment]
We have a css-only solution for back-to-top. The template.js is obsolete and has to be reviewed.
The change in the url is an expected behavior I think.. @hans2103 can you tell more about it?

**Comment by Scrabble96** [comment]
> 
> > The change in the url is an expected behavior I think.. @hans2103 can you tell more about it?

Even if it is expected, it's not a good solution and you will get lots of queries like mine in the future if it stays that way.

If a template.js is required to make this work, why not keep it?
Or, as the js for this is so small, add it to the template inline, but either way, don't use 'var' as that is outdated and should be 'const' or 'let'.

**Comment by hans2103** [comment]
I'm afraid we have to revert the removal of `id="back-top"` to prevent the hashtag in the URL.
The back-to-top works when js fails... the link `href="#top"` works. You'll have #top in the url.
The back-to-top works when js works... current template.js will add preventDefault and scroll window to 0,0. Without #top in the url.  :-(
I'm not aware of a non-js solution to prevent the #top in the url after clicking back-to-top

**Comment by hans2103** [comment]
PR https://github.com/joomla/cassiopeia/pull/244 created

**Comment by chmst** [comment]
Thank you! PR is merged.
