### ISSUE TITLE
Proposal for a jQuery-free alternative to MetisMenu

### ISSUE THREAD

**Issue by Scrabble96** [joomla/cassiopeia#255]
I realise I may just be too late, as you've closed PR48 and have raised a PR for the main Joomla code. However...

### What needs to be fixed
Joomla! 4x should have its own core menu

### Why this should be fixed
MetisMenu relies on jQuery which Joomla 4 is attempting to make redundant
MetisMenu is third-party software that relies on external maintenance
The responsive menu is ‘trapped’ in the header which stretches to fit the vertical menu
Joomla! 4x should have its own menu

### How would you fix it
I have created an alternative menu:

A new menu that:
•	Uses only one set of menu files
•	Multi-level (infinite levels)
•	Clickable and tappable
•	No jQuery
•	Does not use any Bootstrap

**Files:** separator item type duplicated and modified to create new item type ‘separator-line’
•	I have added a type based on ‘separator’ that if it does not have any child items, it will display a line instead of the menu title. This line can be set to not display if required.
Javascript:
•	12 lines to open and close the individual menu items
•	10 lines to close the menu when clicking outside the menu
•	30 lines to open and close the sidenav panel (someone with more than my beginner’s Javascript knowledge could probably reduce this)

**CSS**: I have created several separate files showing different layouts:
•	Horizontal left-to-right (class: hltrmenu)
•	Horizontal right-to-left (hrtlmenu)
•	Bottom horizontal left-to-right opening upwards (class: hbrtlmenu, min-width 929px)
•	Vertical left-to-right (vrtlmenu)
•	A responsive combination of the first layout restricted to min-width 767px and the vertical layout for narrow screens only. (hltrrespmenu)
•	In due course, these could be combined as some of the code is duplicated in each.

**Responsive menus:** Responsive menus have been created using a combination of the horizontal layout and vertical layouts for both the top menu and bottom menu. See demo (below). 
For this, I have added three divs to the main Cassiopeia index.php: 
•	an ‘overlay’ (optional) which casts a semi-transparent grey div over the whole page except for the displayed menu and sidenav panel. 
•	The sidenav panel is the next new div, which opens to 350px wide and 100% high when the burger (menu icon) is clicked or tapped. This could be 100% wide and then the overlay would not be required. The vertical menu is displayed on top of this panel and the site logo above it.
•	The third new div is the burger, currently placed to sit at the bottom of the Cassiopeia header div. On scroll it moves to the bottom of the page.

In my demo, the styling is called by adding the appropriate class in the menu module Advanced tab. If using this system, a new user would not necessarily know which class to use so I would suggest that extra features in the core menu module setup could include the option to choose horizontal, or vertical or both (responsive); right-to-left or left-to-right; top or bottom.
The only issue I have not dealt with yet is the resizing of menu images, as can be seen with the ‘login’ item.
You can view a demonstration here: [https://pr48.websiteprep.co.uk] and feedback would be appreciated.

### Side Effects expected
None once the images are fixed.

**Comment by richard67** [comment]
@Scrabble96 We are using metismenujs, this is already without jQuery.

**Comment by richard67** [comment]
You are wrong with your assumption that we used metismenu with jQuery.

We use metismenujs, the vanilla variant of metismenu. And this is already used in backend by the Atum template, so we do not introduce any new 3rd party dependency.

You can see and read all this in our brand new PR for the CMS repository: [https://github.com/joomla/joomla-cms/pull/31520](https://github.com/joomla/joomla-cms/pull/31520).

But as I said, the same information was already available in this repository here.

Of course it is nice if you have managed to develop an own accessible dropdown menu.

Feel free to make a PR in the CMS repo.

But as with our PR the development here has finished, I close this issue.
