### ISSUE TITLE
[RFC] Shall we rename the "Google Fonts" option to something more general and group fonts by vendors?

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#32]
RFC about changes on PR #18 .

### Problem identified

The use of local fonts is not really limited to Google Fonts.

When PR #18 will be ready we will be able to download and use fonts from any fonts provider or vendor as long as they are available in woff and woff2 format.

So naming the option "Google Fonts" might be at least misleading.

I ask all to suggest a better naming or vote for some suggested by others, so we can see what would be the best, most widely accepted naming.

We could use instead of "Google Fonts" something like:
- 3rd Party Fonts
- Extra Fonts
- Local Fonts
...

Another thing is that we could use fronts from more than one vendor, so it might make sense to group them by vendors in the dropdown, like we now group e.g. the layouts by templates in module's layout selection.

We could use sub-folders to group the scss files (and the compiled css) by the vendors, which would also allow us to build that grouped dropdown options.

E.g. if one adds fonts from a vendor "SomeVendor", there would be following folders for scss and css:
- templates/cassiopeia/scss/fonts/Google
- templates/cassiopeia/scss/fonts/SomeVendor
- templates/cassiopeia/css/fonts/Google
- templates/cassiopeia/css/fonts/SomeVendor

The compile script for the scss can already handle that, i.e. the sub-folders don't need to be hard-coded in the script. It also creates the css folders if they don't exist, based on the scss folders.

In the dropdown one could see something like:
- From Google:
-- josefin-sans
-- montserrat
- From SomeVendor:
-- this-font
-- that-font

### Proposed solution

If desired I can implement it.

### Open questions

See above:
- Is it desired to use more general naming?
- If so, suggest names.
- Is it desired to group fonts selection by vendors?

**Comment by brianteeman** [comment]
1. Grouping by vendor
As a user I wouldnt know the difference so it would be an arbitrary separation

2. Folders
Why are the folders not templates/system/fonts and then the physical files that ship with joomla are available to all templates. A template can then add additional fonts to templates/template_name/fonts.  As it is  right now any template that wanted to use one of the fonts that you are shipping with joomla can not do so and they have to install it again.

(I still dont see why we are shipping fonts anyway)

**Comment by richard67** [comment]
> 2. Folders
> Why are the folders not templates/system/fonts and then the physical files that ship with joomla are available to all templates. A template can then add additional fonts to templates/template_name/fonts.  As it is  right now any template that wanted to use one of the fonts that you are shipping with joomla can not do so and they have to install it again.

Correct. I thought about this issue, too. We should change it that way.

**Comment by richard67** [comment]
Would it then make sense to group the fonts like we now group layouts? I.e. first group "--- From System ---" and second group "--- From <template name> Template ---"?

**Comment by brianteeman** [comment]
Yes perhaps. Although you will still end up with duplicate template font files if you copy the template. I'm still to hear a good reason for joomla or the templates to ship physical fonts

**Comment by richard67** [comment]
Well, correct me if I'm wrong, but since the European Supreme Court has invalidated the Privacy Shield agreement with the US, it is (or will soon be after a certain time for accomodation) not be allowed anymore to store personal data in the US, and the client's IP address is considered to be personal data.

That's at least what I know is the reason behind that decision, which was not mine by the way.

From my point of view it's panic for (almost) nothing, because it's very likely that EU and US have to make a new agreement, and then there will be again no problem to use Google whatever services.

**Comment by brianteeman** [comment]
It is nothing to do with google its the way the internet works. Access something and your ip address is part of the request. By that token you can't host your site on a cdn or on a hosting provider that is not in the EU. Irrespective of where the font is. So are we making joomla.com not available to anyone outside the USA. And that means not just site owners but you would also have to prevent site visitors from outside the USA.  We would also have to change all the help links inside of joomla so that the help content is in the site and not on a remote server as that remote server will also log the ip address and it hasnt asked for permission.
(facepalm)

**Comment by richard67** [comment]
That's why I think they'll find a new agreement.

**Comment by richard67** [comment]
What comes into my mind: Why do we want to **_replace_** the Google fonts option by the local fonts? Why not **_adding_** it so we have 3 options:
- "Standard", that should work like now in J3 when Google Fonts is switched off for the Protostar template.
- "Google fonts" as we have it now in 4.0-dev - if necessary we can add some GDPR warning to that option ;-)
- "Local fonts" (wherever they come from) - if this is selected we see the additonal select for the font

**Comment by chmst** [comment]
Good for me. 

"cassiopeia default font (name)" delivered with cassiopeia in templates/cassiopeia/fonts/ 
"external fonts" (with GDPR warning). 
"local fonts" 

Then all the questions in the german forum about how to get rid from the google fonts are history :) and it is a good argument in the privacy package.

**Comment by richard67** [comment]
> "cassiopeia default font (name)" delivered with cassiopeia in templates/cassiopeia/fonts/

I think you got that wrong. In "templates/cassiopeia/fonts/" we have the fonts for the 3rd option, local fonts, like added here with PR #18 . What I mean with the first option is what you have now when you switch off Google Fonts.

**Comment by richard67** [comment]
@chmst Sorry, have forgotten to explicitely ping you in my previous comment.

**Comment by richard67** [comment]
@chmst Ah, silly me!! There is nothing to be switched off without PR #18 ! Well, option 1 should work like in Protostar in J3 when the Google Fonts are switched off.

**Comment by drmenzelit** [comment]
@chmst in PR #18 I already implemented the switch like in Protostar:
Google Font yes / no
If yes -> load local Google Font
If no -> system font defined by template (in this case by Bootstrap)

**Comment by N6REJ** [comment]
If yes -> load local Google Font
OR -> local font ( use folders )
If no -> system font defined by template (in this case by Bootstrap)

**Comment by richard67** [comment]
@N6REJ Check again my comment above: https://github.com/joomla/cassiopeia/issues/32#issuecomment-676093848

I had the idea for 3 options, but the 2nd one with Google Fonts would not be local, it would be like what is now in J4 in Cassiopeia, without our ongoing works. It would still be called Google Fonts because loading from the Google Fonts API. Only the 3rd option would load local fonts, but these could come from any vendow, not Google only.

If we stay with what we currently have in PR #28 , we would only have off and on, and the local fonts could also come from any vendor, so I'd leave away the word "Google" in this case.

**Comment by N6REJ** [comment]
"Standard", that should work like now in J3 when Google Fonts is switched off for the Protostar template. = will use BS font set.

"Google fonts" as we have it now in 4.0-dev - if necessary we can add some GDPR warning to that option ;-) = will use api ( will require "showon" fields for url & font family

"Local fonts" (wherever they come from) - if this is selected we see the additional select for the font = uses folder system? 

This makes the most sense to me.

You could add "Download font" which would then use the google api to dl locally. Additional fields would allow for other fonts?

**Comment by richard67** [comment]
> You could add "Download font" which would then use the google api to dl locally.

Not sure if we need that. It could blow it up a bit. But other opinions are welcome.

> Additional fields would allow for other fonts?

Additional fields? Which? I'd make it possible to add more local fonts, but that would be more options of a driop down, not additional field. Or did I get your idea wrong?

**Comment by N6REJ** [comment]
when they choose google font ( of any method ) they have to provide 2 fields..
One is font url
Other is font family.
![image](https://user-images.githubusercontent.com/1850089/90682185-368dfc00-e22a-11ea-8908-ddff24d25d3b.png)

**Comment by N6REJ** [comment]
The only way around this is if we provide the list via api call ( many templates do it this way )

**Comment by richard67** [comment]
I do not really want to provide an interface to download the local fonts (3rd option in my list). I only want the drop down to select them being populated with the lost of locally available css files for these fonts without the need to edit the XML file for adding hard-coded options. No need to access any API.

For the Google Fonts option, 2nd option in my list, I do not want the font to be selectable, I want the one font to be used which is now used in J4 in Cassiopeia.

**Comment by richard67** [comment]
Has been solved with PR #61 .
