### ISSUE TITLE
Change HTML structure of the template

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#33]
Change the structure from index.php to adapt to the new design. The names of the positions shouldn't change. We should work with sections instead of div container.

- [x] Logo + Search

- [x] Menu

- [x] Banner -> we can eventually create a new chrome to have an image with text overlay

- [x] Top-A Modul -> Main Features, it can be a custom module or one of the articles module (category, latest, etc.)

- [x] Main Content -> Blog or Featured Layout

<del>- [ ] Bottom-A or Bottom-B -> Custom module, menu</del>

- [x] Footer

<del>- [ ] Login module has to be re-styled.. it looks very J 1.5 ;-)</del>

That is for the "homepage". Later we can go further with the sub-pages.

**Comment by richard67** [comment]
Any of the above points already solved with PR #41 ?

**Comment by richard67** [comment]
Anything which can be checked meanwhile in the to-do list?

**Comment by drmenzelit** [comment]
Further improvements after merging in core.
