### ISSUE TITLE
Card Layout for custom modules 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#35]
### Is your feature request related to a problem? Please describe.
The new design shows modules in a special card layout 

### Describe the solution you'd like
Add and alternative layout

**Comment by hans2103** [comment]
@chmst Is this what you mean with the "special card layout"?

<img width="191" alt="Schermafbeelding 2020-08-21 om 08 10 35" src="https://user-images.githubusercontent.com/639822/90858206-09eef700-e386-11ea-87ec-d39293772417.png">

It's a box with an image and text-area. The text area has a title, body text and an action button.
I would like to suggest to implement the card as described by Heydon Pickering on his pattern library => https://inclusive-components.design/cards/

**Comment by chmst** [comment]
This i in scope of the general design process.
