### ISSUE TITLE
Modules as discs 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#36]
### Is your feature request related to a problem? Please describe.
The new Layout shows a disc layout for modules 

### Describe the solution you'd like
Let we make that by users (bootstrap) or can we add a class or a layout?

**Comment by brianteeman** [comment]
disc???

**Comment by chmst** [comment]
border-radius 50%

**Comment by brianteeman** [comment]
Ah now I understand

**Comment by chmst** [comment]
How would you call this? I did not find the right word

**Comment by brianteeman** [comment]
Well bootstrap just calls it rounded-circle as opposed to rounded-pill
https://getbootstrap.com/docs/4.5/utilities/borders/#border-radius

Can't say I see a need for this

**Comment by richard67** [comment]
> How would you call this? I did not find the right word

Pizza shape? ;-)

**Comment by chmst** [comment]
:) circle without corners? rounded-circle is a pleonasmus - and my home made pizza is rectangular with rounded corners

**Comment by N6REJ** [comment]
@chmst in woodworking its called a biscuit.
![image](https://user-images.githubusercontent.com/1850089/90834709-8515c600-e310-11ea-98ef-6fcd5cb99f17.png) and in normal life an ellipsis.
"The member button is an ellipsis but I'm not sure an elliptical button is the best idea.  The smiley is circular and I'm confident a circle is a much better idea."

**Comment by N6REJ** [comment]
Too make it more confusing, an ellipsis IS circular lol

**Comment by chmst** [comment]
will not be added to cassiopeia
