### ISSUE TITLE
[Metismenu] Since recent scss changes, the active menu item is not visualized anymore

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#47]
Issue for PR #46 .

### Steps to reproduce the issue

Install the latest testing branch and then blog sampe data, see #37 .

Check on frontend by selecting different menu teims if the active item on top level is visualized somehow.

In J4 standard Cassiopeia it looks like underlined, but in fact it was a border. E.g with blog sample data installed, active menu item = "About":
![j4-active-menu-standard](https://user-images.githubusercontent.com/7413183/91658563-7e820e00-eac9-11ea-9779-4cd0d96e8522.png)

In the Cassiopeia development here I think it worked in past (but am not 100% sure), but now it doesn't work anymore:
![j4-active-menu-cassiopeia-missing](https://user-images.githubusercontent.com/7413183/91658573-98235580-eac9-11ea-8180-f65c5646aa15.png)

Ping @hans2103 .

**Comment by drmenzelit** [comment]
Solved in commit #65 8cddf3dbf3a49530a9fdfca2b956a7431e1477c0
I put only another color for the active menu item. I don't know if that is enough. If someone has another idea, feel free.
The version with the "underline" doesn't look good now because of the padding of the li element.

**Comment by richard67** [comment]
Different colors are working with that commit, but the contrast is bad because the wrong colors are used. This can be fixed. But I am not sure if color only is sufficient.

**Comment by drmenzelit** [comment]
We have still several problems with colors and contrast...
And we need to check font-size and font-weight too, that also have an impact in contrast

**Comment by brianteeman** [comment]
Golden rule. Do not rely on a single visual indicator

**Comment by richard67** [comment]
Will be solved with PR #71 , I've tested that with success.
