### ISSUE TITLE
Change template scss variables to css variables

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#51]
The use of css variables instead of scss ones will improve the modularization of the css code. For example we can create a css file for modules stuff that is only loaded when a module is in use.

Examples:
// Global
$cassiopeia-template-color-dark: 
$cassiopeia-template-color: 
$cassiopeia-container-main-bg:
$cassiopeia-border-color: 

can be changed to
// Global
--cassiopeia-template-color-dark: 
--cassiopeia-template-color: 
--cassiopeia-container-main-bg:
--cassiopeia-border-color:

**Comment by drmenzelit** [comment]
**How to implement color switcher**

- Prepare scss/css files for global color definitions
    - summer.scss
        :root {
            --color-primary: #e0a800;
            --color-primary-dark: #d39e00;
            --color-whatever: #000;
        }
    - winter.css
        :root {
            --color-primary: #073f86;
            --color-primary-dark: #03254f;
            --color-whatever: #fff;
        }
    - etc.
- Parameter "color" like font field to select the appropriate css file
- Similar to fonts add code in index.php to load the variables

	$paramsColorName = $this->params->get('colorName');
	$wa->registerAndUseStyle($paramsColorName, 'css/colors/' . $paramsColorName . '.css');
	$this->getPreloadManager()->preload($wa->getAsset('style', $paramsColorName)->getUri(), ['as' => 'style']);

- In all scss files we use the css variables
    section {
        background-color: var(--color-primary);
        color: var(--color-whatever);
    }

**Comment by richard67** [comment]
Promary-dark? Not primary-dark?

**Comment by chmst** [comment]
Is this done? Can it be closed?

**Comment by drmenzelit** [comment]
Done with PR #58
