### ISSUE TITLE
RTL: Missing Space on last Menu-Element

### ISSUE THREAD

**Issue by ghost** [joomla/cassiopeia#52]
### Steps to reproduce the issue
- Add a Smart Search-Module at Position "Search"
- Add a Menu-Module at Position "Menu"
- Compare Space at last Menu-Element between
LTR and
![Screen Shot 2020-09-01 at 10 13 51](https://user-images.githubusercontent.com/70466955/91825536-b493cf00-ec3c-11ea-9c84-5683994b3fc6.png)
RTL
![Screen Shot 2020-09-01 at 10 06 51](https://user-images.githubusercontent.com/70466955/91825580-bcec0a00-ec3c-11ea-8bec-2e88610e4921.png)

### Expected result
Same Space at RTL as at LTR

### Actual result
Missing Space at RTL

### System information (as much as possible)
php: Linux lamp121.cloudaccess.net 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by chmst** [comment]
Please test PR #85

**Comment by ghost** [comment]
test only using patchtester.

**Comment by richard67** [comment]
I can confirm that this issue has been solved with the meanwhile merged PR #85 .

@Formatio-hippocampi If you have beside your installation with the patchtester an additional folder on your webserver which you can use for a new Joomla installation, you can find here a dummy pull request (PR) with a link to an installation package in its description: https://github.com/joomla/cassiopeia/pull/48 . The installation package and the link is regularly updated when new changes have been approved. Just follow the testing instructions in that PR, i.e. install Blog sample data at the end, to see what we already have done. If you find some new issues you can comment in that dummy PR or open a new issue in this repository here.

**Comment by richard67** [comment]
Closing as meanwhile solved in the development branch with PR #85 . Thanks for reporting.
