### ISSUE TITLE
Metismenu

### ISSUE THREAD

**Issue by brianteeman** [joomla/cassiopeia#53]
The metismenu has been implemented as a template override.

This means it is ONLY available to cassiopeia and EVERY template will need to copy it and include it with the files they ship if they want a usable menu.

It should be a core layout and if necessary some additional css for cassiopeia to match that templates style.

Whenever you create an override in a core template it should set off a big warning sign that you're doing something wrong.

**Comment by richard67** [comment]
See also @ciar4n comment here: [https://github.com/joomla/cassiopeia/pull/49#issuecomment-685046982](https://github.com/joomla/cassiopeia/pull/49#issuecomment-685046982).

**Comment by ciar4n** [comment]
> See also @ciar4n comment here: #49 (comment).

Probably not relevant here as that comment is related to how the override is implemented. Brians point is regarding should the core template have overrides or not which is a wider discussion.

**Comment by chmst** [comment]
At the moment this repo is for proofs of concept. And it isgreat success to have now an accessilble dropdown menu. Thanks to all developers. We must discuss this question again when it comes to make the PR ready for Joomla-cms.

**Comment by brianteeman** [comment]
Please dont get me wrong the code is great I just think its in the wrong folder

**Comment by ciar4n** [comment]
I dont see an issue with having overrides in the template. The template dictates design and as a part of that design is it perfectly reasonable to need to override the core view to something more opinionated like this metismenu. Core views should be a semantic base, once it is anything more it becomes a pain to develop against.

**Comment by brianteeman** [comment]
To quote @bembelimen (although I think he was confused at the time)

> The reason is, that otherwise every 3rd party template has to implement the Metis menu, because it's always in the list of the layouts (and not linked to this template)

**Comment by ciar4n** [comment]
> This means it is ONLY available to cassiopeia and EVERY template will need to copy it 

You will need to explain to me how this is true? As I see it, a template will only need to copy it if they want a menu based on metismenu.

**Comment by brianteeman** [comment]
yes that is correct - i am thinking as a user and not a developer

I have my site built with cassiopeia and i have my lovely dropdown menu
I install another template or try to create my own and I need to copy the metis override from cassiopeia to my new template
It is not possible to copy a template override to another template within the UI

If the metis layout was a core layout then there would be no problem. It would be available to every template and you can still create a template specific override.

**Comment by brianteeman** [comment]
The way I see it there are disadvantages to having this layout part of the template and not part of core.
I do not see any advantages to having it part of the template and not part of the core.

Other than physically moving these files from the template to the core I dont see any issue with making this part of the core

**Comment by bembelimen** [comment]
Hi @brianteeman 
probably it's more my lacking language skill, in my head it sounds correct :-) 

Currently we have something like that:
![grafik](https://user-images.githubusercontent.com/1229869/91957837-dc4f6980-ed06-11ea-995c-0d0f04cfc3ff.png)

So that means, it's clear, that it only works with Cassiopeia.

On the other hand, if we have it in core, we would have something like:

![grafik](https://user-images.githubusercontent.com/1229869/91958019-14ef4300-ed07-11ea-9f1a-80baf42f324f.png)

This means, every template out there have to implement something for metis menu, because it's globally available and otherwise it will not work. Which is (in my opinion) not a good thing to force everyone to support metis menu.

**Comment by brianteeman** [comment]
How will it not work - thats where I am obviously missing something

**Comment by bembelimen** [comment]
It _works_ but some styling could (and probably are) missing, if the template does not implement it.

**Comment by brianteeman** [comment]
adding styling to a template is easy for a user
as I stated above copying an override to another template is not.

I guess I just fundamentally believe that core site/admin templates should never use an override and if they do then there is something very wrong

**Comment by ciar4n** [comment]
> I install another template or try to create my own and I need to copy the metis override from cassiopeia to my new template
It is not possible to copy a template override to another template within the UI

I think there needs to a separation of concerns here. How a menu is displayed should be decided by the template. Or at least that should be the default. I agree with @bembelimen in that metismenu in core poses a problem for 3rd party template, certainly if there is options with the UI specific to that menu.

**Comment by brianteeman** [comment]
If you can not create a dropdown menu in core then thats a problem. My understanding was that work with metis was to achieve that

**Comment by ciar4n** [comment]
> I guess I just fundamentally believe that core site/admin templates should never use an override and if they do then there is something very wrong

I don't believe this to be true for the frontend view. Core views should be semantically correct and a good non-opinionated base to create overrides from. As mentioned template dictates the design and as a part of that design is it perfectly reasonable to need to override the core view to something more opinionated. At the end of the day, mine is one opinion among many. What is correct is probably a wider discussion.

**Comment by ciar4n** [comment]
> If you can not create a dropdown menu in core then thats a problem. My understanding was that work with metis was to achieve that.

For me 'dropdowns' are opinionated design and not a concern of core. The template dictates design and therefore dictates that the top menu displays its child items in a dropdown. And why I think metis should be an override in the template, not in core.

**Comment by brianteeman** [comment]
all I can say is think like a user and not a designer

**Comment by ciar4n** [comment]
If designer/developers are properly considered, it is the users that will benefit in the long run

**Comment by drmenzelit** [comment]
That seems to be kind of a philosophical discussion. There are pros and cons for both sides.
We will close the issue now, because metis menu with dropdowns is working in Cassiopeia and that was the goal.
We can reopen it if necessary.
