### ISSUE TITLE
[style] Dark mode in accessibility plugin causes white font on white background

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#66]
### Steps to reproduce the issue
Activate the accessibility plugin. Go to frontend and choose "invert colour" in the plugin. 

### Expected result
Text is white on black.

### Actual result
Text is white on white

![grafik](https://user-images.githubusercontent.com/1035262/92775721-ec1e1c00-f39e-11ea-9891-a7b36e91ba98.png)

### System information (as much as possible)
win10, firefox

**Comment by richard67** [comment]
@chmst Is this with current 4.0-dev? Or with the development branch here? Or with the development-design2 branch of PR #65 ?

**Comment by chmst** [comment]
It is current v4 - not sure if it is in scope of cassiopeia, but the issue is only frontend. The plugin is in discussion and imho should be removed. But if it remains in the system, it is an issue.

**Comment by drmenzelit** [comment]
I have no idea how the plugin works...

**Comment by chmst** [comment]
closed
