### ISSUE TITLE
[style] Input group search 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#67]
### Steps to reproduce the issue
Input group of the search module - rounded corner  vs. input group 

### Expected result
like as i.e. in the login 

### Actual result
<img width="507" alt="input-search" src="https://user-images.githubusercontent.com/1035262/92905326-dacb2300-f423-11ea-8683-7d4f843bceee.PNG">

**Comment by drmenzelit** [comment]
Solved in commit #65 09851fc5a1c48b452f489d59a4a7926168a4847f
Someone has to check the RTL version.
