### ISSUE TITLE
[structure]

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#68]
### Steps to reproduce the issue
Click Autor Login in the menu, or the About.

### Expected result
The whole width of content is used 

### Actual result

<img width="892" alt="not-adjusted" src="https://user-images.githubusercontent.com/1035262/92906155-8c6a5400-f424-11ea-941b-450239a7e8f0.PNG">

**Comment by drmenzelit** [comment]
![grafik](https://user-images.githubusercontent.com/9153168/92914647-1833ae80-f42c-11ea-8cd2-9f121c88055d.png)

That is how it looks on my testing environment

**Comment by richard67** [comment]
@chmst It seems you refer to the development branch, while @drmenzelit work on the design on branch "development-design2" with PR #65 . Could you test design-related stuff with that branch and report in that PR, and optinally make PRs agains that branch, PRs for the PR, so to say?
