### ISSUE TITLE
Clean up mix of $white and color("white") in Cassiopeia's scss files

### ISSUE THREAD

**Issue by richard67** [joomla/cassiopeia#73]
### Steps to reproduce the issue

See https://github.com/joomla/cassiopeia/pull/71#discussion_r487447487 .

### Expected result

Either `$white` or `color("white")` is used, but not both, I'd prefer `$white`.

### Actual result

A mix of  `$white` and `color("white")` is used throughout Cassiopeia's scss files.

### System information (as much as possible)

Current "development" branch of this repository + PR #71 applied = "development-cassiopeia-design" branch.

**Comment by hans2103** [comment]
changed `var(--white)` and `color("white")` by `$white` with commit https://github.com/joomla/cassiopeia/commits/development-cassiopeia-design

**Comment by richard67** [comment]
Solution confirmed.

**Comment by richard67** [comment]
Will be fixed with PR #71 .
