### ISSUE TITLE
Metismenu toggler button is too thin

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#74]
### What needs to be fixed
Te metis menu toggler button for opening/closing the submenu is rather thin. It is not really visible when a menuItem cintains a link and a button.

<img width="283" alt="metismenu-toggler" src="https://user-images.githubusercontent.com/1035262/93026050-59ca8200-f603-11ea-8908-c663d03ab021.PNG">

### Why this should be fixed
Better UX

### How would you fix it
Make the button with contrast color, make the arrow better visible.

**Comment by richard67** [comment]
I have a solution using Fontawesome, but I am not sure if we should make our metismenu depend on Fontawesome.

**Comment by richard67** [comment]
3rd party template devs might want to use our metismenu but not Fontawesome.

**Comment by brianteeman** [comment]
As I said before they currently cannot use it

**Comment by richard67** [comment]
They can if they copy it, and then it is worth a question if it shall depend on Fontawesome or not.

**Comment by richard67** [comment]
Please test and comment PR #82 . If it's ok we can close this issue, but as long as I am not sure if that PR is the best solution I'd like to keep this issue open.

**Comment by richard67** [comment]
Solved by PR #85 .
