### ISSUE TITLE
Check for issues

### ISSUE THREAD

**Issue by helvecio** [joomla/cassiopeia#8]

**Comment by chmst** [comment]
Is ths related to the issue-tracker? Check for open issues for cassioy?peia and accessibility?

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22J4+Frontend+Template%22

**Comment by chmst** [comment]
Assigned to members who are in other groups. We can see if somthing is related to cassiopeia

**Comment by chmst** [comment]
@helvecio 
Can we close this? Or what do we have to for cloing this`?

**Comment by chmst** [comment]
Closing this now
