### ISSUE TITLE
Fluid layout needs design with spacing and margin 

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#80]
### What needs to be fixed
Check the new cassiopeia in fluid mode

### Why this should be fixed
The content block seems to have not enough paddung/margin. Maybe it is because sample texts are not decorative? 

![grafik](https://user-images.githubusercontent.com/1035262/93259426-1fe2b280-f7a0-11ea-8a55-a3da2ce87e66.png)

**Comment by richard67** [comment]
Solved by PR #84 .
