### ISSUE TITLE
single article needs design respecting fulltext imag and intro image, template override for cassiopeia

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#83]
### Steps to reproduce the issue
make articles with intro image, full image 

https://www.msn.com/de-de/nachrichten/politik/nordrhein-westfalen-rechtsextreme-chat-gruppen-bei-polizei-in-nrw-aufgedeckt/ar-BB195F5V?ocid=msedgdhp

### Expected result
Good design in template overrides

**Comment by richard67** [comment]
Hmm I don't get the issue. Could you show with some screenshot what the problem is?

**Comment by chmst** [comment]
If I wrote that it probably was midnight :D. closing this.
