### ISSUE TITLE
templates/cassiopeia/html/mod_menu/metismenu.php

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#9]
### Is your feature request related to a problem? Please describe.
The template cassopeia does not have a accessible drop down menu with n sublevels

### Describe the solution you'd like
Write an alternative layout for the module mod_menu based on the js variant of metismenu
Must be also designed and tested for rtl languages

**Comment by richard67** [comment]
Branch for this work is [https://github.com/joomla/cassiopeia/tree/4.0-dev-metismenu-frontend](https://github.com/joomla/cassiopeia/tree/4.0-dev-metismenu-frontend).

It contains already a first implementation by @hans2103 .

To suggest changes, make PRs against that branch, e.g. like #13 .

I recommend to put the name of the target branch in squared brackets to the beginning of the title, so we can see which PR is for which piece of work (target branch).

**Comment by brianteeman** [comment]
What is the problem that is being solved here. metismenu requires jquery and I "thought" we were working to reduce jquery and not add more. 

It is perfectly possible to create accessible drop down menus with bootstrap 4 and no additional scripts.

I've done it on several sites. The starting point for the code if i remember correctly was by @coolcat-creations https://github.com/coolcat-creations/ccc-mountain/tree/master/ccc-mountain/html/mod_menu

**Comment by hans2103** [comment]
@brianteeman you are correct... MetisMenu requires jQuery. On the other hand, MetisMenuJS does not require jQuery. It is written with Vanilla JS. Joomla 4 administrator uses MetisMenuJS (non-jQuery) and that is the reason why Cassiopeia is going to use MetisMenuJS (non-jQuery)

https://github.com/onokumus/metismenu
https://github.com/onokumus/metismenujs

**Comment by brianteeman** [comment]
Ok

**Comment by chmst** [comment]
As we have a dropdown menu now, This issue can be closed
