### ISSUE TITLE
metismenu submenus vertical and horizontal design

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#91]
### Problem identified
Submenus in the metismenu could have better distance or contrast against the first level of the menu. As a proposal I have added two fake metis menu screens how a solution could look like. 

### Proposed solution 

<img width="273" alt="metismenu-vertical" src="https://user-images.githubusercontent.com/1035262/93574828-31db7580-f999-11ea-97c8-d8e8a324f76f.PNG">

<img width="378" alt="metis-submenu" src="https://user-images.githubusercontent.com/1035262/93574840-34d66600-f999-11ea-8833-918b27de3abd.PNG">

### Open questions
Can we have two different layouts? Vertical and horizontal? 
Meanings?

**Comment by richard67** [comment]
@chmst Your second screnshot shows a change in the position of the submenu dropdown, right? If so, that's missing in the issue description.

**Comment by richard67** [comment]
@chmst Does PR #175 solve this issue completely from your point of view? Or would you like to have more changes?

**Comment by chmst** [comment]
We have a good solution with #175, thank you.
