### ISSUE TITLE
form - labels have wrong margin

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#92]
### Steps to reproduce the issue
Login to the frontend and edit your prfile

The labels seem to be part of the previous input field.

### Expected result
Labels are near to their input field

### Actual result
Labels seem to belong to the field above

![grafik](https://user-images.githubusercontent.com/1035262/93587364-10cf5080-f9aa-11ea-9510-767ab47e8a30.png)

**Comment by chmst** [comment]
https://issues.joomla.org/tracker/joomla-cms/29138

**Comment by drmenzelit** [comment]
Resolved with last commit... hopefully ;-)

**Comment by chmst** [comment]
resolved with pr #99
