### ISSUE TITLE
Images not scaling for iphone (below about 410px) properly

### ISSUE THREAD

**Issue by softforge** [joomla/cassiopeia#93]
### Steps to reproduce the issue
Install the blog data. Use dev tools and inspect the home page as if an iPhone 

### Expected result
Images scale as they have been getting smaller and smaller to fit the panels

### Actual result
Image stops scaling and breaks out of the panel
See image
![images_not_scaling](https://user-images.githubusercontent.com/1078933/93663136-6284e300-fa5d-11ea-8169-b3483c780ee5.PNG)

### System information (as much as possible)
Chrome latest

**Comment by chmst** [comment]
This is due to a wrong layout. The module must be "noCard" Layout. This is fixed for the sample data in PR #96

@drmenzelit Maybe the breakpoint can be changed?  Or the gap 
![grafik](https://user-images.githubusercontent.com/1035262/94074332-5a2ffd80-fdf9-11ea-83e4-dd3baf136c33.png)

**Comment by drmenzelit** [comment]
I can't reproduce the issue... and with my PR should look ok.. but I will check again

**Comment by drmenzelit** [comment]
![image](https://user-images.githubusercontent.com/9153168/94119402-2aabe000-fe4f-11ea-8ddf-aec047cb47ff.png)

That is how it looks at 752px width on my installation... with the noCard layout the news should look ok.

For smaller displays I need to make a PR against CMS to change the min-width of the grid (at the moment 330px).

**Comment by chmst** [comment]
Looks good - i have tested successfully with your PR and with new sample data (module chrome must be noCard)

**Comment by chmst** [comment]
@softforge could you restest please?

**Comment by brianteeman** [comment]
You might find this useful as it lets you test multiple sizes at once

https://chrome.google.com/webstore/detail/responsive-viewer/inmopeiepgfljkpkidclfgbgbmfcennb

**Comment by softforge** [comment]
Test Ok all seems fixed

**Comment by richard67** [comment]
So the issue can be closed?

**Comment by softforge** [comment]
As far as my problem was concerned, yes, great Job!
