### ISSUE TITLE
All menuitems in metismenu submenu are active if one is clicked

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#97]
### Steps to reproduce the issue
You must have a metismenu with a submenu. (Install sample data)
Open a submenu and click on one of the items. The item is opened. Then open again the submenu

### Expected result
The active item is active

### Actual result
All items in the submenu are active

![grafik](https://user-images.githubusercontent.com/1035262/93721936-76326580-fb93-11ea-835e-8b6a18076d77.png)

**Comment by drmenzelit** [comment]
PR #99
