### ISSUE TITLE
Accessibility: Make Links in text visible

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#98]
### Steps to reproduce the issue
Write an article which contains a link. 

### Expected result
The link is visible (underlined) 

### Actual result

Quest: find the link in this text!

![grafik](https://user-images.githubusercontent.com/1035262/93722018-14bec680-fb94-11ea-9eef-f906d9a7fff4.png)

**Comment by drmenzelit** [comment]
PR #99
